### ISSUE TITLE
EnumProvider::randomEnum()  - sometimes null is returned

### ISSUE THREAD

**Issue by WhiteRabbitDE** [Elao/PhpEnums#105]
Hey,

in my fixtures (alice bundle) i use 

`mimeType: <randomEnum(MediaEnum)>`

When running my testsuite, sometimes the error below occures. This happens for other fixtures/enums too. I have this error for about 1-2 weeks now, never had this error before. Im not sure if it is caused by an update of elao/phpenums or another library i updated.

After running the same testsuite again (without chaning anything) he error is gone and the data is generated correctly. Does anyone have an idea what the cause could be ?

```
vendor/elao/enum/src/Bridge/Faker/Provider/EnumProvider.php on line 90

In SimpleObjectGenerator.php line 112:
                                                                               
  An error occurred while generating the fixture "attachment_2" (App\Entity\A  
  ttachment): Return value of Elao\Enum\Bridge\Faker\Provider\EnumProvider::r  
  andomEnum() must implement interface Elao\Enum\EnumInterface, null returned  
                                                                               

In EnumProvider.php line 90:
                                                                               
  Return value of Elao\Enum\Bridge\Faker\Provider\EnumProvider::randomEnum()   
  must implement interface Elao\Enum\EnumInterface, null returned    
```

**Comment by ogizanagi** [comment]
Hi @WhiteRabbitDE . That's weird indeed... Could you show us your enum code?
Did you modified the enum code between two runs (adding or removing values)?

**Comment by ogizanagi** [comment]
Which elao/enum updates did you make these two last weeks?

**Comment by WhiteRabbitDE** [comment]
Just a general Composer Update, so code adjustments in the enums.

**Comment by ogizanagi** [comment]
I meant from which version to which version of this package did you upgrade?

**Comment by WhiteRabbitDE** [comment]
Hey @ogizanagi ,

i did some debugging and found the cause, even if its kind of strange. The enum is loaded correctly and the randomRank generated in my example is 10. What is strange is that this index does not exist in the $instances array. 

How can this happen ? An easy fix would be to check if the random index does exist in the array but i would like to understand the root cause...

![image](https://user-images.githubusercontent.com/34127121/98214735-2c38ef80-1f47-11eb-9f65-61bd67e87178.png)

**Comment by WhiteRabbitDE** [comment]
I think the error is caused by 

```
    public const XLS = 'application/ms-excel';
    public const XLA = 'application/ms-excel';
```
having the same value! This matches the mssing index in the array.

**Comment by WhiteRabbitDE** [comment]
Should i add a failing test for this problem ? Are there any potential problems having two const with the same value that forced the usage of the array_unique ?

**Comment by ogizanagi** [comment]
Hmm I see. I did not account for some "aliases" identifiers. I'd argue those should be filtered from your allowed values. Aren't enum supposed to have a single identifier by nature? This is the one fetched by the var-dumper caster for instance.

I suppose there is no strong argument neither for keeping this `array_unique`, but depending on your logic, this might make a difference. The fact `\count(Enum::values())` would return a different value than expected, due to the same value appearing more than once.

Do you really use these multiple identifiers for a same value as an enum in some place? Or couldn't it be provided as a simple alias you'll filter in `values()` ?

**Comment by ogizanagi** [comment]
But wait, why is `::instances()` returning a an array with a missing index, while already relying on `::values()` already filtering the value?
I mean, the issue is not directly the `array_unique` call: we simply miss an `array_value` call to reset the indices.

**Comment by WhiteRabbitDE** [comment]
> But wait, why is `::instances()` returning a an array with a missing index, while already relying on `::values()` already filtering the value?
> I mean, the issue is not directly the `array_unique` call: we simply miss an `array_value` call to reset the indices.

Now that you mention this ... you are totally right !  The index is not refreshed as seen on my screenshot.
