### ISSUE TITLE
Array and nullability support for API platform

### ISSUE THREAD

**Issue by JenniferSpry** [Elao/PhpEnums#120]
We noticed that the `ElaoEnumType`-Factory does not differentiate between fields that are enum types and those that are arrays of enum types. It also does not add "nullable" to the schema. So all these fields will have the same schema.

```php
    /**
     * @var TestEnum|null
     */
    private $nullable;

    /**
     * @var TestEnum
     */
    private $notNullable;

    /**
     * @var TestEnum[]
     */
    private $enumArray;
```

Would it be ok, if I made a pull request to change that?

**Comment by ogizanagi** [comment]
@JenniferSpry : Please do! I'd appreciate a lot if you can fix this and test on a real-life project, as I'm not familiar with this factory system.

**Comment by JenniferSpry** [comment]
Will do 👍  Probably not till january though.

**Comment by chalasr** [comment]
This can be closed.
