### ISSUE TITLE
AutoDiscoveredValuesTrait take protected constants

### ISSUE THREAD

**Issue by piotrp321** [Elao/PhpEnums#121]
Is it possible to change AutoDiscoveredValuesTrait to take protected constants as values (not only public)  ?

**Comment by ogizanagi** [comment]
Hi @piotrp321 

No as it would goes against the principe of enumerated values that should be publicly discoverable.
Private and protected constants may be used for other needs, internal to the enum class logic, so changing this would be a BC break as well.

But perhaps you could describe a bit more your use-case to see what we can do about it?

**Comment by piotrp321** [comment]
I am define static doc for enum, for example:

/**
 * @method static RowType NORMAL()
 * @method static RowType TABS()
 * @method static RowType COLLAPSE()
 */
 
 
 When you reference the enum class elsewhere, the code editor (IDE) suggests public const. I would like to suggest only the public static method returned enum object.

**Comment by ogizanagi** [comment]
I see. I don't think restricting the visibility for such purpose is justified though. 
Accessing these values directly still is legit and making these private or protected may even break some logic of the integrations provided in this package, as it may try to access it publicly.

I don't know about other IDEs, but PhpStorm already suggests these methods prior to the actual values:

<img width="566" alt="screenshot 2021-01-17 à 10 56 05" src="https://user-images.githubusercontent.com/2211145/104837072-91e41900-58b2-11eb-9238-bb191d573534.png">

<img width="582" alt="screenshot 2021-01-17 à 10 55 56" src="https://user-images.githubusercontent.com/2211145/104837070-901a5580-58b2-11eb-9232-1d249006e0e5.png">
