### ISSUE TITLE
Default value for generated Doctrine types

### ISSUE THREAD

**Issue by mbrodala** [Elao/PhpEnums#130]
Currently there is no way to set a default enum value when using the autogeneration of Doctrine types via configuration. The generated types extend `AbstractEnumType` but the type classes do not implement `onNullFromDatabase()` / `onNullFromPhp()`. Even if they did, they would not know how to retrieve a default value from the related enum class.

Thus I'd suggest an API to define a default value for an enum (e.g. using a new interface). The `AbstractEnumType` could then check for this and use it to implement the mentioned methods to provide defaults.

What do you think?

**Comment by ogizanagi** [comment]
Hi, thanks for this feature request.
However, why would you need a new interface for this need? I think we could provide the default value in the [bundle configuration](https://github.com/Elao/PhpEnums#in-a-symfony-app) instead, and use it when we generate the DBAL type classes, right?
I don't think the default value for your database should appear in any way into the enum class.

**Comment by mbrodala** [comment]
I'd be fine with that approach too. And I see that it would fit rather nicely into the `TypesDumper`.

So you think a new option `default` which is used to implement said methods in the generated type code would be OK? One could not make a difference between DB/PHP here but if necessary one can always implement a custom type class.

**Comment by ogizanagi** [comment]
Since the configuration should target the 80% use-cases and it's rather simple to register your own type yourself, I'm perfectly fine with this suggestion 👍🏻

**Comment by mbrodala** [comment]
@ogizanagi I pushed a first draft in #132 please have a look and let me know if I missed something essential. Afterwards I'll finish with this with tests.
