### ISSUE TITLE
Doctrine type "json_collection" and diff

### ISSUE THREAD

**Issue by notFloran** [Elao/PhpEnums#140]
I try to use the `json_collection` type (https://github.com/Elao/PhpEnums#in-a-symfony-app) : it works well but `doctrine: migration: diff` offers me the same migration permanently. 

While digging a little I came across this issue : https://github.com/dunglas/doctrine-json-odm/pull/43/files

So I try to add `requiresSQLCommentHint` to `AbstractJsonCollectionEnumType` :

```php
abstract class AbstractJsonCollectionEnumType extends JsonType
{
    // ...

    public function requiresSQLCommentHint(AbstractPlatform $platform)
    {
        return true;
    }
}
``` 

And it works.

**Comment by ogizanagi** [comment]
Hmm, the Doctrine [JsonType](https://github.com/doctrine/dbal/blob/8e0fde2b90e3f61361013d1e928621beeea07bc0/src/Types/JsonType.php#L80-L83) defines it differently according to the platform, depending on if it has native support for a json type or not. So I guess you're using PostgreSQL.
I'm not aware of any drawbacks of overwriting it for custom types though, so let's add it.
