### ISSUE TITLE
Add Doctrine ODM types support

### ISSUE THREAD

**Issue by IonBazan** [Elao/PhpEnums#143]
It would be great to see Doctrine ODM integration here.
I've used my own enum types implementation in few projects and would like to share it in a PR which will be provided later this week.

Not sure how to handle the automatic Types generation when using as Symfony Bundle.

**Comment by ogizanagi** [comment]
Hi @IonBazan . This is a good idea, but I think I've never worked with ODM custom types. So I'd greatly appreciate you share your own experience 👍🏻 . 
We'll see how to proceed with type generation once the base types are done.
