### ISSUE TITLE
Enum FQCN as key can be useful and deprecation could be reconsidered

### ISSUE THREAD

**Issue by tigitz** [Elao/PhpEnums#161]
First of all, thanks for this really complete enum library.

While using it in symfony projects I found I could use it conveniently this way:

```php
// in config/packages/elao_enum.php
return static function (ContainerConfigurator $containerConfigurator): void {
    $containerConfigurator->extension(
        'elao_enum',
        [
            'doctrine' => [
                'types' => [
                    ItemType::class => ItemType::class,
                ]
            ]
        ]
    );
};
```

```php
public function __construct(
        #[ORM\Column(type: ItemType::class)]
        ItemType $type,
    ) {
    }
```

This helps maintaining only one concept to identify my enum class and avoids the pitfall of introducing a second concept as the `name`. I can rename my class easily in my IDE and everything stays "connected", no need to manually edit both the class name and the name.

However it seems like identifying the enum class by its FQCN is deprecated and it's recommended to introduce a `name`:
```
Using enum FQCN as keys at path "elao_enum.doctrine.types" is deprecated. Provide the name as keys and add the "class" option for each entry instead
```

Could it be reconsidered given the use case above ?

Thanks in advance.

**Comment by ogizanagi** [comment]
Oh, I see. this is indeed not a case I expected to forbid. The code here:

https://github.com/Elao/PhpEnums/blob/0d1145710e6b1b4d85dc1af60691d9ac461ae54f/src/Bridge/Symfony/Bundle/DependencyInjection/Configuration.php#L57-L59

was only about detecting the previous configuration format. But if the value and the key are the FQCN, there is no issue I guess.
Until we fix this false positive, you can safely ignore the deprecation though, since it'll not break anyway.

**Comment by tigitz** [comment]
Understood thank you.

I let the issue open then until it's fixed.

**Comment by ogizanagi** [comment]
Hi @tigitz . Would #162 work for you?

**Comment by tigitz** [comment]
Yup it works flawlessly !

Just wanted to highlight your quick response (with tests and everything) about this non critical edge-case.

I just sponsored you, have a drink on me :wink:

**Comment by ogizanagi** [comment]
Wow, thank you @tigitz ❤️  Very much appreciated 😳
