### ISSUE TITLE
Phpstan with AbstractIntegerEnumType

### ISSUE THREAD

**Issue by Kleinast** [Elao/PhpEnums#172]
Hi,

I use Elao\Enum\Bridge\Doctrine\DBAL\Types\AbstractIntegerEnumType like this:
 ```
use Elao\Enum\Bridge\Doctrine\DBAL\Types\AbstractIntegerEnumType;

/**
 * @extends AbstractIntegerEnumType<CampaignKpi>
 */
class CampaignKpiType extends AbstractIntegerEnumType
{
    private const NAME = 'tracker_campaign_kpi';

    protected function getEnumClass(): string
    {
        return CampaignKpi::class;
    }

    public function getName(): string
    {
        return self::NAME;
    }
}
```
And I have this error with phpstan:
PHPDoc tag @extends contains generic type Elao\Enum\Bridge\Doctrine\DBAL\Types\AbstractIntegerEnumType<CampaignKpi> but class              
         Elao\Enum\Bridge\Doctrine\DBAL\Types\AbstractIntegerEnumType is not generic.

Do I @extends it wrong this class ? or is it there miss some phpdoc comment on Elao\Enum\Bridge\Doctrine\DBAL\Types\AbstractIntegerEnumType ?

Thx in advance

**Comment by ogizanagi** [comment]
Indeed, it seems we should add:

```php
/**
 * @extends AbstractEnumType<T>
 * @template T of EnumInterface
 */
```

to the `AbstractIntegerEnumType` class: https://phpstan.org/r/0c9e5d20-6ec0-482a-b354-7450f3f9d7cd

Would this work for you?
Could you please provide a PR?

**Comment by Kleinast** [comment]
I can try
