### ISSUE TITLE
NewFeature: Add FlagBag::ALL

### ISSUE THREAD

**Issue by michnovka** [Elao/PhpEnums#180]
Similar to `FlagBag::NONE = 0` wouldn't it be good to have `FlagBag::ALL = -1` ?

I would actually make a new enum:

```php
enum FlagBagValue: int
{
    case None = 0;
    
    case All = -1;
}
```

Then allow it in both `__constructor` and `from` and other functions accepting bits. If `FlagBagValue::All` is used, it should then analyze the underlying enum (as maybe some bit is missing in enum declaration) and treat the case equally as if every single option from the enum was passed.

This analysis could be cached in some static field of `FlagBag`.

**Comment by ogizanagi** [comment]
I would rather add a dedicated static factory like:

```php
    /**
     * @param class-string<\BackedEnum>
     */
    public static function fromAll(string $enum): static
```

which would internally use `FlagBag::getBitmask` (which might become public as well eventually) to get the integer value of all the combined bits to instantiate the bag.

But I'm not much convinced of the use-cases right now.

**Comment by michnovka** [comment]
I have submitted PR https://github.com/Elao/PhpEnums/pull/181 with the implementation, have a look, feel free to deny if you don't like it. But the possibility to create "full" bag, even if some binary flags are missing (see the new `PermissionsMissingBit` enum) is good imo. Whether we allow it in constructor or make a fromAll method does not matter, but we should have that functionality

**Comment by michnovka** [comment]
Thinking about it more, maybe the static factory is a nicer approach. I will reimplement it that way
