### ISSUE TITLE
[Symfony Bridge] ArgumentValueResolverInterface is deprecated since Symfony 6.2

### ISSUE THREAD

**Issue by IonBazan** [Elao/PhpEnums#203]
Following deprecation messages are produced when using `elao/enum` with Symfony 6.2 (beta):

>The "Elao\Enum\Bridge\Symfony\HttpKernel\Controller\ArgumentResolver\BackedEnumValueResolver" class implements "Symfony\Component\HttpKernel\Controller\ArgumentValueResolverInterface" that is deprecated since Symfony 6.2, implement ValueResolverInterface instead.

>The "Elao\Enum\Bridge\Symfony\HttpKernel\Controller\ArgumentResolver\QueryBodyBackedEnumValueResolver" class implements "Symfony\Component\HttpKernel\Controller\ArgumentValueResolverInterface" that is deprecated since Symfony 6.2, implement ValueResolverInterface instead.

**Comment by ogizanagi** [comment]
Hmm, I already attempted to handle this in https://github.com/Elao/PhpEnums/pull/198, but perhaps I missed something.
Did you try with the (yet) unreleased code?

```sh
composer require "elao/enum:^2.x-dev"
```

**Comment by IonBazan** [comment]
Yes, that works fine! Thanks!
