### ISSUE TITLE
Symfony 6.2 deprecation 

### ISSUE THREAD

**Issue by michnovka** [Elao/PhpEnums#206]
Getting this:

```
The "Elao\Enum\Bridge\Symfony\HttpKernel\Controller\ArgumentResolver\BackedEnumValueResolver" class implements "Symfony\Component\HttpKernel\Controller\ArgumentValueResolverInterface" that is deprecated since Symfony 6.2, implement ValueResolverInterface instead.
```

with version 2.1.0 and Symfony 6.2

I thought this was addressed by https://github.com/Elao/PhpEnums/pull/198 but I still see the deprecation in log.

**Comment by ogizanagi** [comment]
Hi. This was fixed in #205 actually. I didn't tag it yet though. Thanks for the reminder, here is the v2.1.1 tag: https://github.com/Elao/PhpEnums/releases/tag/v2.1.1.
