### ISSUE TITLE
Symfony 6.3 deprecations

### ISSUE THREAD

**Issue by laurentmuller** [Elao/PhpEnums#223]
I just updated my project to Symfony 6.3.0. A deprecation is now raised:

`User Deprecated: Method "Symfony\Component\HttpKernel\Bundle\Bundle::build()" might add "void" as a native return type declaration in the future. Do the same in child class "Elao\Enum\Bridge\Symfony\Bundle\ElaoEnumBundle" now to avoid errors or add an explicit @return annotation to suppress this message.`

The deprecation is in the following `ElaoEnumBundle` class. It is just matter to update return type:

Before:
```php
public function build(ContainerBuilder $container)
```
After:
```php
public function build(ContainerBuilder $container): void
```
It seem this is already set in the source code (see #210).

Now is just matter of create a new release.

**Comment by ogizanagi** [comment]
v2.2.0 is now [published](https://github.com/Elao/PhpEnums/releases/tag/v2.2.0). Thank you for the ping

**Comment by laurentmuller** [comment]
You'r welcome. 
Thank You.
