### ISSUE TITLE
Extension is deprecated in Symfony 7.1

### ISSUE THREAD

**Issue by laurentmuller** [Elao/PhpEnums#231]
I just update my project with Symfoy 7.1.

Now, the following depecration is raised:

> User Deprecated: The "Symfony\Component\HttpKernel\DependencyInjection\Extension" class is considered internal since Symfony 7.1, to be deprecated in 8.1; use Symfony\Component\DependencyInjection\Extension\Extension instead. It may change without further notice. You should not use it from "Elao\Enum\Bridge\Symfony\Bundle\DependencyInjection\ElaoEnumExtension".

So, it's just matter of update the `ElaoEnumExtension` class:

Replace: `Symfony\Component\HttpKernel\DependencyInjection\Extension`

By: `Symfony\Component\DependencyInjection\Extension\Extension`

**Comment by ogizanagi** [comment]
Fixed in latest release, [v2.5.0](https://github.com/Elao/PhpEnums/releases/tag/v2.5.0) (inside #232)

Thanks for the report!

**Comment by laurentmuller** [comment]
Good job !
Thank You
