### ISSUE TITLE
Serializable support

### ISSUE THREAD

**Issue by mvrhov** [Elao/PhpEnums#26]
Is there a plan to add serializable interface to abstract class?
This then means that the enum can be serialized to a session or somewhere else.

**Comment by ogizanagi** [comment]
Indeed, this feature totally makes sense to me.
If you want to, don't hesitate to provide a PR. ;)

**Comment by ogizanagi** [comment]
Closing for now. See https://github.com/Elao/PhpEnums/pull/39#issuecomment-381692520
