### ISSUE TITLE
Do not autodiscover private constants

### ISSUE THREAD

**Issue by ogizanagi** [Elao/PhpEnums#34]
[AutoDiscoveredValuesTrait](https://github.com/Elao/PhpEnums/blob/master/src/AutoDiscoveredValuesTrait.php) should not try to autodiscover private (or protected) constants.

---

https://wiki.php.net/rfc/class_const_visibility

**Comment by chalasr** [comment]
Why not protected ones?

**Comment by ogizanagi** [comment]
enum values should be part of the public API, as it's meant to be used for instance when trying to get the enum instance.

**Comment by chalasr** [comment]
indeed, that's used externally. 👍
