### ISSUE TITLE
Consider using ReflectionClass::getConstants

### ISSUE THREAD

**Issue by ogizanagi** [Elao/PhpEnums#5]
I've always hesitated, but we can consider using [this function](http://php.net/manual/fr/reflectionclass.getconstants.php) in order to get the full list of defined constants in the given enumeration type.

Benefits:
- No need to implement `EnumInterface::values` in each enum type.
- Reflects the `\SplEnum` behavior and enumerations in other languages.
- ? :/

Drawbacks:
- Magic
- Cannot define other constants not meant to be used as an enum value. In theory, I'd say it does not matter much, as the only constants that should live inside the enum should be the ones defining enum values... But... there is the case of the `FlaggedEnum` which can also define common flags combinations, whereas only single bit flags are valid values. Can be workaround for this particular case, though.
- The previous point can be workaround by using naming conventions. But naming conventions are a drawback on their own IMHO.

**Comment by chalasr** [comment]
So we could provide a `getPossibleValues()` which would makes use of reflection? (sorry if something similar is already implemented, I can't find it?)?

> Cannot define other constants not meant to be used as an enum value.

People can still override the method which makes use of the function, right?

**Comment by ogizanagi** [comment]
> So we could provide a getPossibleValues() which would makes use of reflection? (sorry if something similar is already implemented, I can't find it?)?

Yes, the default implementation of `getPossibleValues()` (now renamed to `values` (simplified static API)) will use reflection and cache the result for subsequent calls.

> People can still override the method which makes use of the function, right?

Sure. But I'm not sure the idea of letting the user deals with it and have some enumerations behaving differently pleases me. Enumerations should work the same in the big lines IMHO.

But that's really something to consider.

**Comment by chalasr** [comment]
> Enumerations should work the same in the big lines IMHO.

I agree. Considering

> - Cannot define other constants

and

> - Magic

I fear that using this function may cause troubles which would be hard to debug from an end user pov. I would say to stick on the current implementation and don't provide such magic.

It could be interesting to see how similar packages behave on this point though

**Comment by ogizanagi** [comment]
> It could be interesting to see how similar packages behave on this point though

For the record, [myclabs/php-enum](https://github.com/myclabs/php-enum/blob/master/src/Enum.php#L119-L128) uses it blindly.

**Comment by ogizanagi** [comment]
Closing this as I think it'll brings more issues than benefits.

**Comment by mvrhov** [comment]
I also had a custom enum implementation and have used the reflection to get the constants.
However there was a policy, that if you don't want the cont to be included it should be prefixed by __.

e.g something like this.

```php
    public function getAll()
    {
        $r = new \ReflectionClass($this);
        $v = $r->getConstants();

        //remove all not enum constants (the ones prefixed with __)
        $consts = array();
        array_walk($v, function ($value, $key) use (&$consts) {
            if ('__' == substr($key, 0, 2)) {
                return;
            }

            $consts[] = $value;
        });

        return $consts;
    }
```

**Comment by ogizanagi** [comment]
Thanks for sharing your thoughts on this.
Sure, but we don't like much naming conventions, opinionated by definition. I prefer let introduce such conventions in userland if it makes sense for the project/team.
Or perhaps we could provide another base enum class with this feature.

**Comment by mvrhov** [comment]
Well if this is in a default base class. everybody can overwrite get values if it doesn't like the behavior. As this behavior might be wrong in just a few cases. on contrary without providing this everybody has to implement `values`  function

**Comment by mvrhov** [comment]
One nice thing I had implemented by this is __default const which pointed to one of the other constants. This meant that the enum cannot be nullable as default value would be returned in such case.

**Comment by chalasr** [comment]
> Well if this is in a default base class. everybody can overwrite get values

That's the opposite to me. Better have a default base class that gives the minimal required behavior and no potentially unwanted ones at all, and let the consumer do its custom logic, or provide some other extension points specific to these behaviors (traits, sub base classes..).

**Comment by ogizanagi** [comment]
I eventually came to providing a trait for this. See #32.
