### ISSUE TITLE
php-translation/extractor bridge/extractor

### ISSUE THREAD

**Issue by ostrolucky** [Elao/PhpEnums#51]
Hey, I'm interested to build translation extractor for this library. I would like to know first if such contribution is welcome.

If you are not familiar with [php-translation/extractor](https://github.com/php-translation/extractor), what it would do here is to extract all labels from Enum classes.

**Comment by ogizanagi** [comment]
Yes I would welcome such a thing. Thanks for proposing!

**Comment by ostrolucky** [comment]
This is blocked until https://github.com/Elao/PhpEnums/issues/46 is resolved
