### ISSUE TITLE
Each enum value should be a singleton

### ISSUE THREAD

**Issue by ogizanagi** [Elao/PhpEnums#6]
In theory, each enumeration value should live only once in the application.
If I create twice `Gender::create(Gender::MALE)`, I must obtain the exact same instance.

For flagged enums, each combination is also a single instance.

It'll allow to compare two enums using `===` instead of `equals` (which can be used for other means actually) and reflects how enumerations behaves in other languages.

This is achievable by caching instances inside a static property on the base enum class, as done with the bitmasks in the FlaggedEnum.

**Comment by benji07** [comment]
👍
