### ISSUE TITLE
Provide integration with NelmioApiDocBundle / provide extractor for Symfony's PropertyInfo component

### ISSUE THREAD

**Issue by Koc** [Elao/PhpEnums#69]
I've tryed describe my api response with type `PriceItemChangesCollection`. Each price item has enumed property and I've got en exception

```
* @SWG\Response(response=200, @Model(type=PriceItemChangesCollection::class), description="")
```

```
LogicException:
The PropertyInfo component was not able to guess the type of App\Model\Enum\Condition::$value

  at vendor/nelmio/api-doc-bundle/ModelDescriber/ObjectModelDescriber.php:82
  at Nelmio\ApiDocBundle\ModelDescriber\ObjectModelDescriber->describe(object(Model), object(Schema))
     (vendor/nelmio/api-doc-bundle/Model/ModelRegistry.php:95)
  at Nelmio\ApiDocBundle\Model\ModelRegistry->registerDefinitions()
     (vendor/nelmio/api-doc-bundle/ApiDocGenerator.php:72)
  at Nelmio\ApiDocBundle\ApiDocGenerator->generate()
     (vendor/nelmio/api-doc-bundle/Controller/SwaggerUiController.php:53)
  at Nelmio\ApiDocBundle\Controller\SwaggerUiController->__invoke(object(Request), 'default')
     (vendor/symfony/http-kernel/HttpKernel.php:149)
  at Symfony\Component\HttpKernel\HttpKernel->handleRaw(object(Request), 1)
     (vendor/symfony/http-kernel/HttpKernel.php:66)
  at Symfony\Component\HttpKernel\HttpKernel->handle(object(Request), 1, true)
     (vendor/symfony/http-kernel/Kernel.php:188)
  at Symfony\Component\HttpKernel\Kernel->handle(object(Request))
     (public/index.php:37)
```

Is it possible provide integration with NelmioApiDocBundle?

**Comment by ogizanagi** [comment]
Hi @Koc 👋  This feature request makes sense.
Which version do you use? Long time I didn't use Nelmio Api doc, but I may have a look if you don't. But I'd recommend supporting 3.0 only.

**Comment by Koc** [comment]
I'm using 3.0 version. But as I understand, problem not in NelmioApiDocBundle but in property info component. Maybe we should create another extractor which implements `\Symfony\Component\PropertyInfo\PropertyTypeExtractorInterface`.

**Comment by arkonchik** [comment]
I have the same issue when i using MyCLabs\Enum\Enum
Property info component try to extract value(have mixed type), and key(no property, only getter) property.
How can I describe child class like this
```
<?php
declare(strict_types=1);

namespace App\Api\Enum;

use MyCLabs\Enum\Enum;use Symfony\Component\Validator\Constraints as Assert;

/**
 * @method self STUDENT_TAXI()
 */
class SomeClass extends Enum
{
    public const CONST_NAME_1 = '1';
}

```
that PropertyInfo did not try extract value and ket properties and get only consts to describe enum possible values?

**Comment by JirkoK** [comment]
Hi,

for nelmio/api-doc-bundle 4.1.1 I had the same problem (elao/enum 1.13.0).
A class with a property of type "elao enum" causes error:
The PropertyInfo component was not able to guess the type of XXX\EnumClass::$value. You may need to add a `@var` annotation or use `@OA\Property(type="")` to make its type explicit.

nelmio can not describe these types.
My solution is:
implement a describer and register it for your project:

```
use Elao\Enum\EnumInterface;
use Elao\Enum\ReadableEnumInterface;
use Nelmio\ApiDocBundle\PropertyDescriber\NullablePropertyTrait;
use Nelmio\ApiDocBundle\PropertyDescriber\PropertyDescriberInterface;
use OpenApi\Annotations\Schema;
use Symfony\Component\PropertyInfo\Type;

class EnumPropertyDescriber implements PropertyDescriberInterface
{
    use NullablePropertyTrait;

    public function describe(array $types, Schema $property, array $groups = null)
    {
        $className = $types[0]->getClassName();
        $property->type = 'string';
        $property->enum = $className::values();
        if (is_a($className, ReadableEnumInterface::class, true)) {
            $a = array_combine($className::values(), $className::readables());
            $property->description = '';
            foreach ($a as $key => $value) {
                $property->description .= sprintf("%s: %s<br/>", $key, $value);
            }
        }
        $this->setNullableProperty($types[0], $property);
    }

    public function supports(array $types): bool
    {
        return 1 === count($types)
            && Type::BUILTIN_TYPE_OBJECT === $types[0]->getBuiltinType()
            && is_a($types[0]->getClassName(), EnumInterface::class, true);
    }
}
```
and register in services.yml:
```
  XXX\EnumPropertyDescriber:
    class: XXX\EnumPropertyDescriber
    tags: ['nelmio_api_doc.object_model.property_describer']
```

@ogizanagi So, maybe you can provide a Describer in your Bundle like Elao\Enum\Bridge\ApiPlatform\Core\JsonSchema\Type\ElaoEnumType 
along with documentation how to setup this.

Thanks for your work at this package.
Greetings
Jirko

**Comment by ogizanagi** [comment]
Hi @JirkoK , thank you very much for your feedback!

As I didn't work with NelmioApiDocBundle since ages, I'm not the most experienced for providing this.
I could re-use the code you shared to us, but you're (or anybody working with this bundle) most likely to provide a good quality implementation with all the use-cases in mind.

So I'd gladly accept a PR if anyone is willing to work on this :)

**Comment by ogizanagi** [comment]
Closing as we might not need this for 2.x using native PHP 8.1 enum (support should go directly in related libs) and 1.x is mostly closed for new features.
