### ISSUE TITLE
callback in validator component 

### ISSUE THREAD

**Issue by ektarum** [Elao/PhpEnums#70]
Hi.

In the validator component, the docs say you can use callback of choice but the constructor of [Elao\Enum\Bridge\Symfony\Validator\Constraint](https://github.com/Elao/PhpEnums/blob/d9744c14cbaf70fddf4beb1931cd2d5a2fad08e6/src/Bridge/Symfony/Validator/Constraint/Enum.php) doesn't permit to define proper callback.

The callback is overwritten if you don't fill choices.

Is it a feature or just a bug ?

Thanks in advance.

**Comment by ogizanagi** [comment]
Hi @ektarum . Thanks for this issue.
This looks like a bug to me: if you provide a callback explicitly, we should use use it.

I may have a look a this in next days, but if you want to contribute to fix this issue, that'd be appreciated :)

**Comment by kevinlelo** [comment]
Hi,

I think I've found a fix for this. Can I submit a pull request?

**Comment by ogizanagi** [comment]
Hi @kevinlelo 👋 
Sorry I missed your comment, thx for the mention.
Please do!

**Comment by chalasr** [comment]
Fixed by #78, right?

**Comment by ogizanagi** [comment]
Indeed, good catch. Thx @chalasr
