### ISSUE TITLE
Error when adding fieldType to setParameter in queryBuilder

### ISSUE THREAD

**Issue by WhiteRabbitDE** [Elao/PhpEnums#83]
Im using this Enum class in an api-platform project. In the new release, the fieldType is added to the setParameter method of the QueryBuilder e.g.
              
```
$queryBuilder
->andWhere(sprintf($wrapCase('%s.%s').' = '.$wrapCase(':%s'), $alias, $field,))
 ->setParameter($valueParameter, $value, $fieldType);

```

This causes an error in the AbstractEnumTyp
```
Error : Call to a member function getValue() on string
vendor\elao\enum\src\Bridge\Doctrine\DBAL\Types\AbstractEnumType.php:55
```
The entity property is
``` 
/**
     * @var MediaEnum
     * @ORM\Column(name="MIME_TYPE", type="mediaEnum", length=255)
 */
    private $mimeType;
```

and the mediaEnum looks like this
```
final class MediaEnum extends Enum
{
    use AutoDiscoveredValuesTrait;

    //Video ENUMS
    public const MP4 = 'video/mp4';
    public const MPG = 'video/mpeg';
}
```

I would appreciate any help or ideas.

**Comment by pluk77** [comment]
Just to be sure, have you configured the doctrine types as well?

    @ORM\Column(name="MIME_TYPE", type="mediaEnum", length=255)

This type should refer to a doctrine type defined in elao_enum.yaml

And what does your GetMimeType() function look like, including annotation?

**Comment by WhiteRabbitDE** [comment]
Here are the other configs
```
class MediaEnumType extends AbstractEnumType
{
    public const NAME = 'mediaEnum';

    protected function getEnumClass(): string
    {
        return MediaEnum::class;
    }

    public function getName(): string
    {
        return static::NAME;
    }
}
```

```
#elao_enum.yaml
elao_enum:
    doctrine:
        types:
            App\Enum\MediaEnum: mediaEnum
```

The Getter and Setter looks like this
```
    public function getMimeType(): MediaEnum
    {
        return $this->mimeType;
    }

    public function setMimeType(MediaEnum $mimeType): void
    {
        $this->mimeType = $mimeType;
    }
```

**Comment by WhiteRabbitDE** [comment]
The enums are working fine until i the $fieldType was added as a parameter. This change was introduced in the new api platform version.

Before that, i was able to search and filter on enum fields.

**Comment by ogizanagi** [comment]
Hi @WhiteRabbitDE . Could you try getting the value of this `$fieldType` ? Were does it come from?

It seems like `$value` is the enum value (not an enum instance). if `$fieldType` properly detected the dbal type, that's why it is failing, as the DBAL type is used to convert the enum instance to its value, but got a string here.
Without the `setParameter` type argument, it worked by comparing values as scalars directly.

Is there a way for you to get an enum instance instead of the raw value in your filters?
There is an enum normalizer for this, but I'm not sure the serializer is used for filters in api-platform.

**Comment by WhiteRabbitDE** [comment]
The value of $fieldType is "mediaEnum".  The value comes from this method 
```
    protected function getDoctrineFieldType(string $property, string $resourceClass)
    {
        $propertyParts = $this->splitPropertyParts($property, $resourceClass);
        $metadata = $this->getNestedMetadata($resourceClass, $propertyParts['associations']);

        return $metadata->getTypeOfField($propertyParts['field']);
    }
```

> Is there a way for you to get an enum instance instead of the raw value in your filters?
I dont think so.

Is the normalizer part of this project ? But it is registered by default i guess ?

**Comment by ogizanagi** [comment]
I'm afraid there is not much we can do here about this issue. I think you may need a [custom filter](https://api-platform.com/docs/core/filters/#creating-custom-filters).
If you happen to create something generic enough, I'll appreciate if you contribute this custom filter to this package, so anyone using Api platform & `elao/enum` can benefit from it later.

**Comment by WhiteRabbitDE** [comment]
Thanks for the investigation @ogizanagi . I wrote a custom filter and it works, it's basically just the same SearchFilter but without the fieldType ... 

I can put up a PR to add this to the library but there seems to be other issues with the SearchFilter changes in api platform. Maybe we dont need to add the custom filter in the end if the problem is fixed somehow.

**Comment by ogizanagi** [comment]
Any integration goes into the bridge directory: https://github.com/Elao/PhpEnums/tree/master/src/Bridge
You could create a `ApiPlatform\Core\JsonSchema\Type` sub-namespace in it for instance.

> I can put up a PR to add this to the library but there seems to be other issues with the SearchFilter changes in api platform. Maybe we dont need to add the custom filter in the end if the problem is fixed somehow.

Let's wait then. Keep me in touch ;)

**Comment by alOneh** [comment]
I faced the same issue last week, and implement a custom EnumFilter if @WhiteRabbitDE is not on it, I can make a PR with it.

**Comment by WhiteRabbitDE** [comment]
Since the API Platform Release 2.5.6 , the problem does not exist anymore since they reverted to "problematic" commit.

What version are you using that is still causing this error?

**Comment by alOneh** [comment]
@WhiteRabbitDE 2.5.5

**Comment by alOneh** [comment]
Let me try it out

**Comment by ogizanagi** [comment]
So as I understand it, https://github.com/api-platform/core/pull/3331 originally caused the issue but was reverted in 2.5.6, so everything is working fine for now with latest patch version.
Though, it seems it'll be reintroduced somehow later, with deprecations in https://github.com/api-platform/core/pull/3521.
Before loosing energy to provide a solution that might not be the final one, I'd recommend to wait for https://github.com/api-platform/core/pull/3521 to be merged.

**Comment by alOneh** [comment]
In my case, 2.5.6 fixed my issue so I'm ok with it
