### ISSUE TITLE
TypesDumper - Extends

### ISSUE THREAD

**Issue by yvalentin** [Elao/PhpEnums#86]
Hi !

I want to know if it will be possible to extends the TypesDumper class to override getSQLDeclaration method ?

Thanks

https://github.com/Elao/PhpEnums/blob/3afa22c65bad1822c2c535c870f8f45c76509e43/src/Bridge/Symfony/Bundle/DependencyInjection/Compiler/DoctrineDBALTypesPass.php#L35

**Comment by ogizanagi** [comment]
Hi @yvalentin !

For most advanced usages, I'd recommend to simply write your DBAL type yourself by extending one of the base ones provided in this package.
But we might consider adding some configuration for specific things. What is your need exactly? Why do you want to override this method?

**Comment by yvalentin** [comment]
Yes! Indeed, I will be possible by extending `Elao\Enum\Bridge\Doctrine\DBAL\Types\AbstractEnumType` class.

I would like to have real enum type without create a `DBAL type` class for each types.
Before the update of `elao/PhpEnums` with `TypesDumper.php` class, we create `DBAL type` class with:
```php
public function getSQLDeclaration(array $fieldDeclaration, AbstractPlatform $platform): string
{
    $values = implode(', ', array_map(function ($value) { return "'$value'";}, Gender::values()));

    return "ENUM($values)";
}
```
And the result was a real enum on mariadb. I have updated this lib and remove all my `DBAL type` class know we have `VARCHAR`.
I would like to keep `ENUM` on my migration files without create a `DBAL type` class each time i need a type.

**Comment by ogizanagi** [comment]
Alright. Handling the enum db type is actually something I'd like to provide as a feature directly in this package, so you won't have to override this method and we don't need to add dedicated feature to override it.

Instead, I'd suggest a global `doctrine.enum_sql_declaration` flag in (`false` by default) used to enable the `ENUM` SQL declaration while generating the types, as well as a way to opt-in/opt-out per type.

Would you like to provide a PR for this?
